name: "deepclusterv2-imagenet100"
method: "deepclusterv2"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  num_prototypes: [3000, 3000, 3000]
data:
  dataset: imagenet100
  train_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/train"
  val_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.6
  classifier_lr: 0.1
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
  min_lr: 0.0006
  warmup_start_lr: 0.0
  warmup_epochs: 11
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
dali:
  encode_indexes_into_labels: True
augmentations_cfg: "scripts/configs/defaults/augmentations/symmetric/default.yaml"
wandb_cfg: "scripts/configs/defaults/wandb/private.yaml"
# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16