name: "dino-vit-imagenet100"
method: "dino"
backbone:
  name: "vit_tiny"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 65536
  norm_last_layer: False
momentum:
  base_tau: 0.9995
  final_tau: 1.0
data:
  dataset: imagenet100
  train_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/train"
  val_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "adamw"
  batch_size: 64
  lr: 0.005
  classifier_lr: 3e-3
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
dali:
  encode_indexes_into_labels: True
augmentations_cfg: "scripts/configs/defaults/augmentations/asymmetric/default.yaml"
wandb_cfg: "scripts/configs/defaults/wandb/private.yaml"
# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16