name: "mae-imagenet100"
method: "mae"
backbone:
  name: "vit_base"
method_kwargs:
  decoder_embed_dim: 512
  decoder_depth: 8
  decoder_num_heads: 16
  mask_ratio: 0.75
  norm_pix_loss: True
momentum:
  base_tau: 0.9995
  final_tau: 1.0
data:
  dataset: imagenet100
  train_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/train"
  val_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "adamw"
  batch_size: 64
  lr: 2.0e-4
  classifier_lr: 2.0e-4
  weight_decay: 0.05
  kwargs:
    beta1: 0.9
    beta2: 0.95
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
dali:
  encode_indexes_into_labels: True
augmentations_cfg: "scripts/configs/defaults/augmentations/reconstruction.yaml"
wandb_cfg: "scripts/configs/defaults/wandb/private.yaml"
# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16