name: "mocov2plus-imagenet100"
method: "mocov2plus"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  queue_size: 65536
  temperature: 0.2
  base_tau_momentum: 0.99
  final_tau_momentum: 0.999
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: imagenet100
  train_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/train"
  val_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 64
  lr: 0.3
  classifier_lr: 0.3
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
augmentations_cfg: "scripts/configs/defaults/augmentations/symmetric_weak.yaml"
wandb_cfg: "scripts/configs/defaults/wandb/private.yaml"
# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16