name: "mocov3-imagenet100"
method: "mocov3"
backbone:
  name: "vit_small"
method_kwargs:
  proj_hidden_dim: 4096
  pred_hidden_dim: 4096
  temperature: 0.2
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: imagenet100
  train_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/train"
  val_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet-100/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "adamw"
  batch_size: 64
  lr: 3.0e-4
  classifier_lr: 3.0e-4
  weight_decay: 0.1
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
augmentations_cfg: "scripts/configs/defaults/augmentations/asymmetric/default.yaml"
wandb_cfg: "scripts/configs/defaults/wandb/private.yaml"
# overwrite PL stuff
max_epochs: 400
devices: [0, 1, 2, 3, 4, 5, 6, 7]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16