name: "byol-imagenet"
method: "byol"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: imagenet
  train_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet/train"
  val_path: "/home/CORP/vg.turrisi/Documents/datasets/imagenet/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.45
  classifier_lr: 0.2
  weight_decay: 1e-6
  kwargs:
    clip_lr: False
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
augmentations_cfg: "scripts/configs/defaults/augmentations/asymmetric/default.yaml"
wandb_cfg: "scripts/configs/defaults/wandb/private.yaml"
# overwrite PL stuff
max_epochs: 100
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
accumulate_grad_batches: 16